export var playerColors: string[] = [
  "#FFFF3C",
  "#FF423D",
  "#3CFF4B",
  "#3C43FF",
  "#FF9E3C",
  "#5DFFFF",
  "#E51B5F",
  "#EF3CFF",
  "#FFFFFF",
  "#AAAAAA",
  "#585858",
  "#B0AE2F",
  "#FFE79E",
  "#E0FFD0",
  "#FFE4FF",
  "#B7BBFF",
];

export var ammoGroupMap: object = {
  MIS_CH1: "MIS_CH1",
  MIS_CH2: "MIS_CH1",
  MIS_CH3: "MIS_CH1",
  MIS_CH4: "MIS_CH1",
  MIS_AA1: "MIS_AA1",
  MIS_AA2: "MIS_AA1",
  MIS_AA3: "MIS_AA1",
  MIS_AA4: "MIS_AA1",
  MIS_HL1: "MIS_HL1",
  MIS_HL2: "MIS_HL1",
  MIS_HL3: "MIS_HL1",
  MIS_SL1: "MIS_SL1",
  MIS_SL2: "MIS_SL1",
  MIS_SL3: "MIS_SL1",
  MIS_SR1: "MIS_SR1",
  MIS_SR2: "MIS_SR1",
  MIS_SR3: "MIS_SR1",
  MIS_SR4: "MIS_SR1",
  MIS_MR1: "MIS_MR1",
  MIS_MR2: "MIS_MR1",
  MIS_MR3: "MIS_MR1",
  MIS_MR4: "MIS_MR1",
  MIS_HR1: "MIS_HR4",
  MIS_HR2: "MIS_HR4",
  MIS_HR3: "MIS_HR4",
  MIS_HR4: "MIS_HR4",
  MIS_EDG1: "MIS_EDG1",
  MIS_UCS_SR1: "MIS_UCS_SR1",
  MIS_UCS_SR2: "MIS_UCS_SR1",
  MIS_UCS_SR3: "MIS_UCS_SR1",
  MIS_UCS_SR4: "MIS_UCS_SR1",
  MIS_SC1: "MIS_SC1",
  MIS_SC2: "MIS_SC1",
  MIS_SC3: "MIS_SC1",
  MIS_SC4: "MIS_SC1",
  MIS_HC1: "MIS_HC1",
  MIS_HC2: "MIS_HC1",
  MIS_HC3: "MIS_HC1",
  MIS_HC4: "MIS_HC1",
  MIS_G1: "MIS_G1",
  MIS_G2: "MIS_G1",
  MIS_G3: "MIS_G1",
  MIS_G4: "MIS_G1",
  MIS_SP: "MIS_SP",
  MIS_HP: "MIS_HP",
  MIS_HPG: "MIS_HP",
  MIS_PCP: "MIS_PCP",
  MIS_EDART: "MIS_EDART",
  MIS_UCSART: "MIS_UCSART",
};

export var chassisGroupMap: object = {
  EDUST1: "EDUST",
  EDUST2: "EDUST",
  EDUST3: "EDUST",
  EDUMT1: "EDUMT",
  EDUMT2: "EDUMT",
  EDUMT3: "EDUMT",
  EDUHT1: "EDUHT",
  EDUHT2: "EDUHT",
  EDUHT3: "EDUHT",
  EDUBT1: "EDUBT",
  EDUBT2: "EDUBT",
  EDUA11: "EDUA1",
  EDUA12: "EDUA1",
  EDUA21: "EDUA2",
  EDUA22: "EDUA2",
  EDUA31: "EDUA3",
  EDUA32: "EDUA3",
  EDUA41: "EDUA4",
  EDUA42: "EDUA4",
  EDUOH1: "EDUOH1",
  EDUOH2: "EDUOH1",
  EDUBU1: "EDUBU1",
  EDUAS1: "EDUAS1",
  EDUOB: "EDUOB",
  EDUOB2: "EDUOB",
  UCSUHL1: "UCSUHL1",
  UCSUHL2: "UCSUHL1",
  UCSUHL3: "UCSUHL1",
  UCSUAS1: "UCSUAS1",
  UCSUBU1: "UCSUBU1",
  UCSUSL1: "UCSUSL1",
  UCSUSL2: "UCSUSL1",
  UCSUSL3: "UCSUSL1",
  UCSUML1: "UCSUML1",
  UCSUML2: "UCSUML1",
  UCSUML3: "UCSUML1",
  UCSUOB: "UCSUOB",
  UCSUOB2: "UCSUOB",
};

export var weaponGroupMap: object = {
  EDWCH1: 'EDWCH',
  EDWCH2: 'EDWCH',
  EDWAC1: 'EDWCH',
  EDWAC2: 'EDWCH',
  EDWAA1: "EDWAA1",
  EDWCA1: "EDWCA",
  EDWCA2: "EDWCA",
  EDWHC1: "EDWHC",
  EDWHC2: "EDWHC",
  EDWART: "EDWART",
  EDWSR1: "EDWSR",
  EDWSR2: "EDWSR",
  EDWSR3: "EDWSR",
  EDWSR1AB: "EDWSR",
  EDWSR2AB: "EDWSR",
  EDWMR1: "EDWMR",
  EDWMR2: "EDWMR",
  EDWMR3: "EDWMR",
  EDWHR1: "EDWHR1",
  EDWSL1: "EDWSL",
  EDWSL2: "EDWSL",
  EDWSL3: "EDWSL",
  EDWHL1: "EDWHL",
  EDWHL2: "EDWHL",
  EDWHL3: "EDWHL",
  EDWAR1: "EDWSR",
  EDWAR2: "EDWSR",
  EDWAMR1: "EDWMR",
  EDWAMR2: "EDWMR",
  EDWAB1: "EDWAB",
  EDWAB2: "EDWAB",
  EDBANNER: "EDBANNER",
  EDWAN1: "EDWAN1",
  EDSCREAMER1: "EDSCREAMER",
  EDSCREAMER2: "EDSCREAMER",
  EDSCREAMER3: "EDSCREAMER",

  UCSWTSG1: "UCSWTSG",
  UCSWTSG2: "UCSWTSG",
  UCSWTSP1: "UCSWTSP",
  UCSWTSP2: "UCSWTSP",
  UCSWSSP1: "UCSWTSP",
  UCSWSSP2: "UCSWTSP",
  UCSWBHP1: "UCSWBHP",
  UCSWBHP2: "UCSWBHP",
  UCSWBHP3: "UCSWBHP",
  UCSBANNER: "UCSBANNER",
}

export function formatDecimal (num: number): string {
  return Intl.NumberFormat("en-US", {minimumFractionDigits: 1, maximumFractionDigits: 1}).format(num);
};

export function formatDamage (num: number): string {
  return Intl.NumberFormat("en-US", {minimumFractionDigits: 1, maximumFractionDigits: 1}).format(num / 1000) +"K";
};

export function formatInt (num: number): string {
  return Intl.NumberFormat("en-US").format(num);
};